spring.application.name=LMSsystem
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# OAuth2 / Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/lms-realm
spring.security.oauth2.client.registration.keycloak.client-id=lms-client
spring.security.oauth2.client.registration.keycloak.client-secret=01It5zXdfmSnKBG9H6X6BVXzpin2u8Go
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/lms-realm

keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8081}
keycloak.realm=${KEYCLOAK_REALM:lms-realm}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:lms-client}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:01It5zXdfmSnKBG9H6X6BVXzpin2u8Go}